server:
  port: 8080
spring:
  application:
    name: ztk-oauth-auth-server
  redis:
    database: 1
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 0